#!/usr/bin/env python3
"""
Backfill Summaries to ChromaDB

One-time operation to archive existing SQLite conversation summaries into
ChromaDB so they become searchable via archival_memory_search and
conversation_search.

These summaries were generated by the background summary trigger but never
made it to ChromaDB because only the context-window-overflow trigger had
the archival step. This script closes that gap.

Usage:
    python scripts/backfill_summaries.py [--dry-run] [--session-id default]

Options:
    --dry-run       Preview what would be archived without writing to ChromaDB
    --session-id    Only backfill summaries for a specific session (default: all)
"""

import os
import sys
import time
import argparse

# Add backend to path
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND_DIR = os.path.join(REPO_ROOT, 'backend')
sys.path.insert(0, BACKEND_DIR)

from dotenv import load_dotenv
load_dotenv(os.path.join(REPO_ROOT, '.env'))
load_dotenv(os.path.join(BACKEND_DIR, '.env'))

from core.state_manager import StateManager
from core.memory_system import MemorySystem
from tools.memory_tools import MemoryTools


def get_chromadb_path():
    """Resolve ChromaDB path the same way the server does."""
    return os.getenv("CHROMADB_PATH", os.path.join(BACKEND_DIR, "data", "chromadb"))


def get_sqlite_path():
    """Resolve SQLite path the same way the server does."""
    return os.getenv("SQLITE_DB_PATH", os.path.join(BACKEND_DIR, "data", "db", "substrate_state.db"))


def run_backfill(dry_run: bool = False, session_id: str = None):
    """
    Backfill existing summaries from SQLite to ChromaDB.

    Args:
        dry_run: If True, preview without writing
        session_id: Optional filter to a specific session
    """
    print("\n" + "=" * 60)
    print("  BACKFILL SUMMARIES TO CHROMADB")
    print(f"  Mode: {'DRY RUN (no changes)' if dry_run else 'LIVE (writing to ChromaDB)'}")
    print(f"  Session filter: {session_id or 'all'}")
    print("=" * 60)

    # Initialize systems
    chromadb_path = get_chromadb_path()
    sqlite_path = get_sqlite_path()
    print(f"\n  ChromaDB path: {chromadb_path}")
    print(f"  SQLite path: {sqlite_path}")

    # Set CHROMADB_PATH so MemoryTools picks up the right location
    os.environ.setdefault("CHROMADB_PATH", chromadb_path)

    state = StateManager(db_path=sqlite_path)
    memory = MemorySystem(chromadb_path=chromadb_path)
    memory_tools = MemoryTools(state, memory_system=memory)

    # Get all summaries from SQLite
    print("\nLoading summaries from SQLite...")
    import sqlite3
    conn = sqlite3.connect(state.db_path)
    cursor = conn.cursor()
    if session_id:
        cursor.execute("""
            SELECT id, session_id, summary, created_at, from_timestamp,
                   to_timestamp, message_count, token_count
            FROM conversation_summaries
            WHERE session_id = ?
            ORDER BY created_at ASC
        """, (session_id,))
    else:
        cursor.execute("""
            SELECT id, session_id, summary, created_at, from_timestamp,
                   to_timestamp, message_count, token_count
            FROM conversation_summaries
            ORDER BY created_at ASC
        """)
    summaries = cursor.fetchall()
    conn.close()

    total = len(summaries)
    print(f"  Found {total} summaries in SQLite")

    if total == 0:
        print("\nNo summaries to backfill.")
        return

    # Process summaries
    archived = 0
    failed = 0
    start_time = time.time()

    for row in summaries:
        summary_id, sess_id, summary_text, created_at, from_ts, to_ts, msg_count, token_count = row

        archive_text = f"📅 Conversation Summary ({from_ts} - {to_ts})\n\n{summary_text}\n\n---\n📊 Stats: {msg_count} messages summarized"

        content_preview = summary_text[:60].replace('\n', ' ')
        print(f"  [#{summary_id}] {from_ts} → {to_ts} ({msg_count} msgs) \"{content_preview}...\"")

        if dry_run:
            archived += 1
            continue

        try:
            result = memory_tools.archival_memory_insert(
                content=archive_text,
                category="insight",
                importance=6,
                tags=[
                    'conversation_summary',
                    'source:backfill',
                    'reflections'
                ],
                metadata={
                    'type': 'conversation_summary',
                    'source': 'backfill',
                    'session_id': sess_id,
                    'summary_id': summary_id,
                    'from_timestamp': from_ts,
                    'to_timestamp': to_ts,
                    'message_count': msg_count,
                    'created_at': created_at,
                }
            )
            if result.get('status') == 'OK':
                archived += 1
                print(f"    ✅ [{archived}/{total}] Archived ({result.get('memory_id', 'unknown')})")
            else:
                print(f"    ❌ FAILED: {result.get('message', 'unknown error')}")
                failed += 1
        except Exception as e:
            print(f"    ❌ FAILED: {e}")
            failed += 1

    elapsed = time.time() - start_time

    print(f"\n{'=' * 60}")
    print(f"  BACKFILL COMPLETE")
    print(f"  Archived: {archived}")
    print(f"  Failed: {failed}")
    print(f"  Total: {total}")
    print(f"  Time: {elapsed:.1f}s")
    print(f"  Mode: {'DRY RUN (no changes)' if dry_run else 'LIVE (ChromaDB updated)'}")
    print(f"{'=' * 60}")


def main():
    parser = argparse.ArgumentParser(description="Backfill existing summaries to ChromaDB")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing to ChromaDB")
    parser.add_argument("--session-id", type=str, default=None, help="Only backfill a specific session")
    args = parser.parse_args()

    run_backfill(dry_run=args.dry_run, session_id=args.session_id)


if __name__ == "__main__":
    main()
